# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kevin/code/Image_Processing_Project1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kevin/code/Image_Processing_Project1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/code/Image_Processing_Project1/CMakeFiles /home/kevin/code/Image_Processing_Project1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/code/Image_Processing_Project1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cv_version

# Build rule for target.
cv_version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cv_version
.PHONY : cv_version

# fast build rule for target.
cv_version/fast:
	$(MAKE) -f CMakeFiles/cv_version.dir/build.make CMakeFiles/cv_version.dir/build
.PHONY : cv_version/fast

#=============================================================================
# Target rules for targets named ImageProject1

# Build rule for target.
ImageProject1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImageProject1
.PHONY : ImageProject1

# fast build rule for target.
ImageProject1/fast:
	$(MAKE) -f CMakeFiles/ImageProject1.dir/build.make CMakeFiles/ImageProject1.dir/build
.PHONY : ImageProject1/fast

src/cv_version.o: src/cv_version.cpp.o

.PHONY : src/cv_version.o

# target to build an object file
src/cv_version.cpp.o:
	$(MAKE) -f CMakeFiles/cv_version.dir/build.make CMakeFiles/cv_version.dir/src/cv_version.cpp.o
.PHONY : src/cv_version.cpp.o

src/cv_version.i: src/cv_version.cpp.i

.PHONY : src/cv_version.i

# target to preprocess a source file
src/cv_version.cpp.i:
	$(MAKE) -f CMakeFiles/cv_version.dir/build.make CMakeFiles/cv_version.dir/src/cv_version.cpp.i
.PHONY : src/cv_version.cpp.i

src/cv_version.s: src/cv_version.cpp.s

.PHONY : src/cv_version.s

# target to generate assembly for a file
src/cv_version.cpp.s:
	$(MAKE) -f CMakeFiles/cv_version.dir/build.make CMakeFiles/cv_version.dir/src/cv_version.cpp.s
.PHONY : src/cv_version.cpp.s

src/demo_code.o: src/demo_code.cpp.o

.PHONY : src/demo_code.o

# target to build an object file
src/demo_code.cpp.o:
	$(MAKE) -f CMakeFiles/ImageProject1.dir/build.make CMakeFiles/ImageProject1.dir/src/demo_code.cpp.o
.PHONY : src/demo_code.cpp.o

src/demo_code.i: src/demo_code.cpp.i

.PHONY : src/demo_code.i

# target to preprocess a source file
src/demo_code.cpp.i:
	$(MAKE) -f CMakeFiles/ImageProject1.dir/build.make CMakeFiles/ImageProject1.dir/src/demo_code.cpp.i
.PHONY : src/demo_code.cpp.i

src/demo_code.s: src/demo_code.cpp.s

.PHONY : src/demo_code.s

# target to generate assembly for a file
src/demo_code.cpp.s:
	$(MAKE) -f CMakeFiles/ImageProject1.dir/build.make CMakeFiles/ImageProject1.dir/src/demo_code.cpp.s
.PHONY : src/demo_code.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... cv_version"
	@echo "... rebuild_cache"
	@echo "... ImageProject1"
	@echo "... src/cv_version.o"
	@echo "... src/cv_version.i"
	@echo "... src/cv_version.s"
	@echo "... src/demo_code.o"
	@echo "... src/demo_code.i"
	@echo "... src/demo_code.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

